CREATE TABLE Bettor (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  username VARCHAR(10) NOT NULL,
  password VARCHAR(200) NOT NULL,
  CONSTRAINT username_UNIQUE UNIQUE (username)
);