spring.application.name=bettracker

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bettracker_db}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bettracker_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bettracker_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:UomFJOOOpTOFWsoX10lE2kSfmGcRfF48OWy59ReisGM}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER:bettracker}