spring.application.name=bettracker

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bettracker_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bettracker_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bettracker_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:UomFJOOOpTOFWsoX10lE2kSfmGcRfF48OWy59ReisGM}
api.security.token.issuer=${API_SECURITY_TOKEN_ISSUER:bettracker}

# Spring Mail Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6631d6108fbed9
spring.mail.password=bdc14741b6e65d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.email.sender=noreply@bettracker.com

# Google Cloud Console
google.client-id=870620479665-jvk490ihjk81kplequgovd8fi8o9ep0v.apps.googleusercontent.com